# Generated by Django 3.0.3 on 2020-03-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_library_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
