# Generated by Django 3.0.3 on 2020-03-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_library_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
